version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    container_name: netvis-frontend
  backend:
    build:
      context: ./backend
    container_name: netvis-backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
        POSTGRES_HOST: database
        POSTGRES_PORT: 5432
        POSTGRES_DB: netvis
        POSTGRES_USER: netvis
        POSTGRES_PASSWORD: netvis

     

  database:
    build:
      context: ./database
    container_name: netvis-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: netvis
      POSTGRES_PASSWORD: netvis
      POSTGRES_DB: netvis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
