version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    # Temporarily disable volume to avoid npm issue
    # volumes:
    #   - ./frontend:/app
    working_dir: /app
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./database:/database          # <-- Mount external database code
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/database     # <-- Add PYTHONPATH so imports work
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  database:
    build:
      context: ./database
    container_name: netvis-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: netvis
      POSTGRES_PASSWORD: netvis
      POSTGRES_DB: netvis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
